---

- name: "Copy file to the server"
  become: true
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: "Unzip copied file"
  become: true
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: "Install and run npm"
  become: true
  shell: |
    sudo apt install -y npm
    sudo npm install
    pm2 stop default
    pm2 start npm -- start
